// app/components/layout/Footer.tsx
import LinkButton from '../ui/LinkButton'
import Nav from './Nav'

export const SocialLinks = {
	Github: 'https://github.com/soumakkdev',
	LinkedIn: 'https://www.linkedin.com/in/soumakkdutta/',
	X: 'https://x.com/soumakkdev',
}

export default function Footer() {
	return (
		<section className="max-w-6xl mx-auto px-6 mt-20 mb-8 border-t border-border pt-8">
			<div className="flex justify-between flex-col gap-5 lg:flex-row">
				<Nav />
				{/* <div className="flex gap-8">
					<LinkButton hideArrow href={SocialLinks.Github} target="_blank" rel="noreferrer" text="Github" />
					<LinkButton
						hideArrow
						href={SocialLinks.LinkedIn}
						target="_blank"
						rel="noreferrer"
						text="LinkedIn"
					/>
					<LinkButton hideArrow href="/resume.pdf" target="_blank" rel="noreferrer" text="Resume" />
					<LinkButton hideArrow href="mailto:soumakkdutta@gmail.com" text="Email me" />
				</div> */}

				<p className="text-sm text-muted-foreground">&copy; {new Date().getFullYear()} Soumak Dutta</p>
			</div>
		</section>
	)
}

// src/layout/Footer.svelte
<script>
	let emailId = 'soumakkdutta@gmail.com';
	let year = new Date().getFullYear();
	let social = {
		twitter: 'https://twitter.com/soumakkdev',
		github: 'https://github.com/soumakkdev'
	};
</script>

<footer>
	<div class="flex items-center justify-between p-4">
		<a href="mailto:{emailId}">{emailId}</a>

		<nav class="space-x-4">
			<a href={social.twitter} target="_blank" rel="noreferrer">Twitter</a>
			<a href={social.github} target="_blank" rel="noreferrer">GitHub</a>
		</nav>

		<p>&copy; soumak {year}</p>
	</div>
</footer>
